### ISSUE TITLE
Test data quality

### ISSUE THREAD

**Issue by alemela** [synapta/validatore-XML-190#3]
### singolo campo singolo lotto
- [X] non nullo su tutto tranne [warn] data fine, importo liquidato, aggiudicatario, partecipante
- [X] cig valida algoritmo
- [X] [warn] ragonesocialeprop >=3 caratteri
- [X] [warn] oggetto con almeno 3 parole distinte (parola = cosa separata da spazi)
- [x] più di 500 partecipanti
- [X] codfiscprop regex
- [ ] [warn] caratteri utf-8
- [ ] scelta contraente da elenco
- [X] importo formato NNNNNNNNN.DD (non inizia per 0)
- [X] [warn] importo = 0
- [X] [warn] se >= 10B
- [X] date nel formato giusto ISO 8601 2020-02-31
- [X] [warn] date imprecise (anno a sole 2 cifre)
- [X] date > 2000 < 2100 (date in questo secolo)
- [ ] partecipanti non duplicati come cf
- [ ] raggruppamento 2+ membri
- [ ] 2+ aggiudicatari (no raggruppamento)
- [ ] ruoli dei raggruppamenti da lista
- [ ] [warn] 2+ mandataria, capogruppo

### multi campo singolo lotto
- [X] [warn] almeno un lotto
- [X] data fine >= data inizio
- [ ] pa stessa tra partecipanti
- [X] [warn] importo liquidato >= 2* importo
- [ ] vincitore uguale a pa banditrice
- [ ] (later) soldi coerenti col tipo di procedura
- [ ] (later) nome azienda non coerente con la piva
- [ ] pagato ma nessun partecipante
- [ ] vincitori non coerenti col tipo di procedura / oggetto (difficile)
- [ ] l'aggiudicatario deve essere tra i partecipanti

### singolo campo multi lotto
- [ ] non mescolati CF e nomi azienda multilotto
- [ ] CIG non ripetute cross lotti tranne 0000000000
- [ ] [warn] più del 80% degli importi sono divisibili per 100 mod 0

### multi campo multi lotto
- [ ] [warn] due lotti uguali forse copy-paste
- [ ] [warn] importo che è una data o una partita iva del file

**Comment by sofiarosati** [comment]
- soldi coerenti col tipo di procedura
- nome azienda non coerente con la piva 
- pagato ma nessun partecipante
- vincitore uguale a pa banditrice
- vincitori non coerenti col tipo di procedura / oggetto (difficile)
