### ISSUE TITLE
Some of the tested docs have old xmlns declaration 

### ISSUE THREAD

**Issue by baldoalessandro** [synapta/validatore-XML-190#6]
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<legge190:pubblicazione xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:legge190="legge190_1_0" xsi:schemaLocation="legge190_1_0 http://dati.avcp.it/schema/datasetAppaltiL190.xsd">
	<metadata>
		<titolo> ... </titolo>
```
This is the incriminated ns: ` xmlns:legge190="legge190_1_0" xsi:schemaLocation="legge190_1_0 http://dati.avcp.it/schema/datasetAppaltiL190.xsd"` (404) referring to the old institution.
It should be converted to [http://dati.anticorruzione.it/schema/datasetAppaltiL190.xsd](http://dati.anticorruzione.it/schema/datasetAppaltiL190.xsd)

**Comment by sofiarosati** [comment]
The application uses now a static version of the xsd schema.
